#!/usr/bin/env python3
"""Theme storage: named color themes (light + dark) live in themes/<id>.json and
are the single source of truth shared by the project's two renderers:

  * render_hero.py  — static README hero SVGs (reads the appearance dicts directly)
  * docs/themes.css — web dashboard CSS variables (generated by this module)

A theme file is `{id, label, light: {...}, dark: {...}}`; each appearance carries
the same color keys (see _CSS_VARS plus `ramp` and `shadow`). To add a theme, drop
a new themes/<id>.json beside ember.json with the same shape.

Usage:  python3 themes.py            # regenerate docs/themes.css from the active theme
        python3 themes.py --theme ember
"""
from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
THEMES_DIR = os.path.join(ROOT, "themes")
DEFAULT_THEME = "monospace"
APPEARANCES = ("light", "dark")

# Non-color "look" tokens — shared across a theme's light + dark appearances.
# Defaults reproduce the original Ember look, so a theme can omit `look` (or any
# field) and nothing changes. `svgFont` defaults to None: the SVG renderer falls
# back to its own system-sans stack (GitHub-rendered SVGs can't load web fonts).
DEFAULT_LOOK = {
    "fontBody": "-apple-system, BlinkMacSystemFont, \"Segoe UI\", Helvetica, Arial, sans-serif",
    "svgFont": None,
    "radiusScale": 1,
    "borderWidth": "1px",
    "uppercase": False,
    "tabularNums": False,
    "fontImport": "",
    "mono": False,  # SVG-only: widen the hero number's unit advance for fixed-width fonts
}


def load_theme(theme_id: str = DEFAULT_THEME) -> dict:
    """Return the parsed theme: {id, label, look, light: {...}, dark: {...}}."""
    with open(os.path.join(THEMES_DIR, f"{theme_id}.json")) as f:
        return json.load(f)


def resolve_look(theme: dict) -> dict:
    """Theme's `look` merged over DEFAULT_LOOK, so missing fields fall back."""
    return {**DEFAULT_LOOK, **theme.get("look", {})}


def available_themes() -> list[str]:
    """Sorted ids of every theme in themes/."""
    return sorted(f[:-5] for f in os.listdir(THEMES_DIR) if f.endswith(".json"))


# theme key -> CSS custom property. `ramp` expands to --l1..--l4 and `shadow`
# maps to --shadow separately below (they aren't plain 1:1 strings).
_CSS_VARS = [
    ("bg", "--bg"),
    ("panel", "--panel"),
    ("panel2", "--panel-2"),
    ("stroke", "--stroke"),
    ("text", "--text"),
    ("muted", "--muted"),
    ("faint", "--faint"),
    ("accent", "--accent"),
    ("claude", "--claude"),
    ("codex", "--codex"),
    ("empty", "--empty"),
]


def _vars_block(appearance: dict, indent: str) -> str:
    lines = [f"{indent}{var}: {appearance[key]};" for key, var in _CSS_VARS]
    lines += [f"{indent}--l{i}: {c};" for i, c in enumerate(appearance["ramp"], 1)]
    lines.append(f"{indent}--shadow: {appearance['shadow']};")
    return "\n".join(lines)


def _look_block(look: dict, indent: str) -> str:
    """Look tokens consumed by styles.css. Shared across light/dark, so emitted
    once in :root. `--radius-scale` multiplies every border-radius (1 = original,
    0 = square); `--ut`/`--num` gate uppercasing and tabular numerals."""
    return "\n".join([
        f"{indent}--font-body: {look['fontBody']};",
        f"{indent}--radius-scale: {look['radiusScale']};",
        f"{indent}--border-width: {look['borderWidth']};",
        f"{indent}--ut: {'uppercase' if look['uppercase'] else 'none'};",
        f"{indent}--num: {'tabular-nums lining-nums' if look['tabularNums'] else 'normal'};",
    ])


def to_css(theme: dict) -> str:
    """Render :root (light colors + shared look) + a prefers-color-scheme:dark
    color override for a theme, plus an optional web-font @import."""
    look = resolve_look(theme)
    # @import must precede every rule except @charset; a comment is allowed before it.
    font_import = f"@import url('{look['fontImport']}');\n" if look["fontImport"] else ""
    root = _vars_block(theme["light"], "  ") + "\n" + _look_block(look, "  ")
    return (
        f"/* GENERATED by themes.py from themes/{theme['id']}.json — do not edit by hand.\n"
        f"   Active theme: {theme['label']} ({theme['id']}). "
        f"Light + dark via prefers-color-scheme. */\n"
        f"{font_import}"
        f":root {{\n{root}\n}}\n"
        f"@media (prefers-color-scheme: dark) {{\n"
        f"  :root {{\n{_vars_block(theme['dark'], '    ')}\n  }}\n"
        f"}}\n"
    )


def write_css(theme_id: str = DEFAULT_THEME, out_path: str | None = None) -> str:
    if out_path is None:
        out_path = os.path.join(ROOT, "docs", "themes.css")
    css = to_css(load_theme(theme_id))
    tmp = out_path + ".tmp"
    with open(tmp, "w") as f:
        f.write(css)
    os.replace(tmp, out_path)
    return out_path


def main() -> None:
    import argparse

    ap = argparse.ArgumentParser(description="Generate docs/themes.css from a theme.")
    ap.add_argument("--theme", default=DEFAULT_THEME,
                    help=f"theme id in themes/ (have: {', '.join(available_themes())})")
    args = ap.parse_args()
    path = write_css(args.theme)
    print(f"wrote {path}  (theme: {args.theme})")


if __name__ == "__main__":
    main()
