#!/usr/bin/env python3
"""Theme storage: named color themes (light + dark) live in themes/<id>.json and
are the single source of truth shared by the project's two renderers:

  * render_hero.py  — static README hero SVGs (reads the appearance dicts directly)
  * docs/themes.css — web dashboard CSS variables (generated by this module)

A theme file is `{id, label, light: {...}, dark: {...}}`; each appearance carries
the same color keys (see _CSS_VARS plus `ramp` and `shadow`). To add a theme, drop
a new themes/<id>.json beside ember.json with the same shape.

Usage:  python3 themes.py            # regenerate docs/themes.css from the active theme
        python3 themes.py --theme ember
"""
from __future__ import annotations

import json
import os

ROOT = os.path.dirname(os.path.abspath(__file__))
THEMES_DIR = os.path.join(ROOT, "themes")
DEFAULT_THEME = "ember"
APPEARANCES = ("light", "dark")


def load_theme(theme_id: str = DEFAULT_THEME) -> dict:
    """Return the parsed theme: {id, label, light: {...}, dark: {...}}."""
    with open(os.path.join(THEMES_DIR, f"{theme_id}.json")) as f:
        return json.load(f)


def available_themes() -> list[str]:
    """Sorted ids of every theme in themes/."""
    return sorted(f[:-5] for f in os.listdir(THEMES_DIR) if f.endswith(".json"))


# theme key -> CSS custom property. `ramp` expands to --l1..--l4 and `shadow`
# maps to --shadow separately below (they aren't plain 1:1 strings).
_CSS_VARS = [
    ("bg", "--bg"),
    ("panel", "--panel"),
    ("panel2", "--panel-2"),
    ("stroke", "--stroke"),
    ("text", "--text"),
    ("muted", "--muted"),
    ("faint", "--faint"),
    ("accent", "--accent"),
    ("claude", "--claude"),
    ("codex", "--codex"),
    ("empty", "--empty"),
]


def _vars_block(appearance: dict, indent: str) -> str:
    lines = [f"{indent}{var}: {appearance[key]};" for key, var in _CSS_VARS]
    lines += [f"{indent}--l{i}: {c};" for i, c in enumerate(appearance["ramp"], 1)]
    lines.append(f"{indent}--shadow: {appearance['shadow']};")
    return "\n".join(lines)


def to_css(theme: dict) -> str:
    """Render :root (light) + a prefers-color-scheme:dark override for a theme."""
    return (
        f"/* GENERATED by themes.py from themes/{theme['id']}.json — do not edit by hand.\n"
        f"   Active theme: {theme['label']} ({theme['id']}). "
        f"Light + dark via prefers-color-scheme. */\n"
        f":root {{\n{_vars_block(theme['light'], '  ')}\n}}\n"
        f"@media (prefers-color-scheme: dark) {{\n"
        f"  :root {{\n{_vars_block(theme['dark'], '    ')}\n  }}\n"
        f"}}\n"
    )


def write_css(theme_id: str = DEFAULT_THEME, out_path: str | None = None) -> str:
    if out_path is None:
        out_path = os.path.join(ROOT, "docs", "themes.css")
    css = to_css(load_theme(theme_id))
    tmp = out_path + ".tmp"
    with open(tmp, "w") as f:
        f.write(css)
    os.replace(tmp, out_path)
    return out_path


def main() -> None:
    import argparse

    ap = argparse.ArgumentParser(description="Generate docs/themes.css from a theme.")
    ap.add_argument("--theme", default=DEFAULT_THEME,
                    help=f"theme id in themes/ (have: {', '.join(available_themes())})")
    args = ap.parse_args()
    path = write_css(args.theme)
    print(f"wrote {path}  (theme: {args.theme})")


if __name__ == "__main__":
    main()
